// Code generated by "stringer -type=NodeType -linecomment"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeVariableDef-0]
	_ = x[NodeVariableDec-1]
	_ = x[NodeValueDef-2]
	_ = x[NodeIfStatement-3]
	_ = x[NodeElsifStatement-4]
	_ = x[NodeElseStatement-5]
	_ = x[NodeRoot-6]
	_ = x[NodeBinOp-7]
	_ = x[NodeNumLit-8]
	_ = x[NodeLit-9]
	_ = x[NodeIndex-10]
	_ = x[NodeI64Type-11]
	_ = x[NodeI32Type-12]
	_ = x[NodeI16Type-13]
	_ = x[NodeI8Type-14]
	_ = x[NodeU64Type-15]
	_ = x[NodeU32Type-16]
	_ = x[NodeU16Type-17]
	_ = x[NodeU8Type-18]
	_ = x[NodeStrType-19]
	_ = x[NodeBoolType-20]
	_ = x[NodeAnyType-21]
}

const _NodeType_name = "variable defvariable decvalue defif statementelsif statementNodeElseStatementrootbin opnum literalliteralindexI64 typeI32 typeI16 typeI8 typeU64 typeU32 typeU16 typeU8 typeStr typeBool typeAny type"

var _NodeType_index = [...]uint8{0, 12, 24, 33, 45, 60, 77, 81, 87, 98, 105, 110, 118, 126, 134, 141, 149, 157, 165, 172, 180, 189, 197}

func (i NodeType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NodeType_index)-1 {
		return "NodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeType_name[_NodeType_index[idx]:_NodeType_index[idx+1]]
}
